module.exports = {
    CHANGE_STATUS_SUCCESS: 'Cập nhật trạng thái thành công!',
    DELETE_SUCCESS       : 'Xóa phần tử thành công!',
    CHANGE_ORDERING_SUCCESS: 'Cập nhật Ordering thành công!',
    CHANGE_STATUS_MULTI_SUCCESS: 'Cập nhật trạng thái của %d phần tử thành công!',
    DELETE_MULTI_SUCCESS: 'Xóa của %d phần tử thành công!',
    CHANGE_GROUPS_SUCCESS: 'Cập nhật groups thành công!',
    ADD_SUCCESS: 'Thêm mới phần tử thành công!',
    EDIT_SUCCESS: 'Cập nhật phần tử thành công!',
    ERROR_NAME: 'Vui lòng nhập tên trong khoảng %d đến %d kí tự!',
    ERROR_ORDERING: 'Vui lòng nhập ordering trong khoảng %d đến %d kí tự!',
    ERROR_STATUS: 'Vui lòng chọn 1 trạng thái!',
    CHANGE_GROUPS_SUCCESS: 'Vui lòng chọn ảnh hợp lệ!',
    ERROR_FULLNAME:'Vui lòng chọn tên hợp lệ!',
    ERROR_USERNAME:'Vui lòng chọn tên đăng nhập hợp lệ!',
    ERROR_PASSWORD:'Vui lòng chọn tên mật khẩu hợp lệ!',
    ERROR_EMAIL:'Vui lòng chọn email hợp lệ!',
    ERROR_GROUP:'Vui lòng chọn nhóm hợp lệ!',
}