module.exports = {
    CHANGE_STATUS_SUCCESS: 'Cập nhật trạng thái thành công!',
    DELETE_SUCCESS       : 'Xóa phần tử thành công!',
    CHANGE_ORDERING_SUCCESS: 'Cập nhật Ordering thành công!',
    CHANGE_STATUS_MULTI_SUCCESS: 'Cập nhật trạng thái của %d phần tử thành công!',
    DELETE_MULTI_SUCCESS: 'Xóa của %d phần tử thành công!',
    CHANGE_GROUPS_SUCCESS: 'Cập nhật groups thành công!',
    ADD_SUCCESS: 'Thêm mới phần tử thành công!',
    EDIT_SUCCESS: 'Cập nhật phần tử thành công!',
    ERROR_NAME: 'Vui lòng nhập tên trong khoảng %d đến %d kí tự!',
    ERROR_NAME_DUPLICATED:'Duplicated Name',
    ERROR_SLUG_DUPLICATED:"Duplicated slug",
    ERROR_ORDERING: 'Vui lòng nhập ordering trong khoảng %d đến %d kí tự!',
    ERROR_STATUS: 'Vui lòng chọn 1 trạng thái!',
    CHANGE_AVARTAR: 'Vui lòng chọn ảnh hợp lệ!',
    ERROR_FULLNAME:'Vui lòng chọn tên hợp lệ!',
    ERROR_USERNAME:'Vui lòng chọn tên đăng nhập hợp lệ!',
    ERROR_PASSWORD:'Vui lòng chọn tên mật khẩu hợp lệ!',
    ERROR_EMAIL:'Vui lòng chọn email hợp lệ!',
    ERROR_GROUP:'Vui lòng chọn nhóm hợp lệ!',
    ERROR_NOT_IMAGE:'Vui lòng chọn ảnh',
    ERROR_PASSWORD:'Vui lòng nhập mật khẩu',
    ERROR_USERNAME:'Vui lòng nhập user name',
    ERROR_UPLOAD_FILE:'Vui lòng Upload lại file',
    ERROR_CATEGORY:'Vui lòng chọn loại bản tin',
    ERROR_POSTION:'Vui lòng chọn một vị trí ',
    CHANGE_POSITION_SUCCESS:'Cập nhật vị trí thành công ',
    CHANGE_CATEGORY_SUCCESS:'Cập nhật category thành công',
    ERROR_DESCRIPTION:'Vui lòng nhập mô tả trong khoảng %d đến %d kí tự!',
    ERROR_DETAIL:'Vui lòng mô tả chi tiết',
    ERROR_CATEGORY_INVALID:'category invalid',
    ERROR_QUANITY:'Vui lòng nhập số lượng',
    ERROR_FILE_EXTENSION:'ERROR_FILE_EXTENSION',
    ERROR_FILE_EMPTY:'ERROR_FILE_EMPTY',
    ERROR_DISCOUNT_MONEY:'ERROR_DISCOUNT_MONEY',
    ERROR_DISCOUNT_PERCENT:'ERROR_DISCOUNT_PERCENT',
    ERROR_DISCOUNT_LISTPRODUCT:'ERROR_DISCOUNT_LISTPRODUCT',
    ERROR_DISCOUNT_LISTPRODUCT_INVALID:'ERROR_DISCOUNT_LISTPRODUCT_INVALID',
    ERROR_DISCOUNT_UNIT:'ERROR_DISCOUNT_UNIT',
    ERROR_ORDER_STATUS:'ERROR_ORDER_STATUS',
    ERROR_ORDER_STATUS_CHANGE:'ERROR_ORDER_STATUS_CHANGE',
    ERROR_COST:'ERROR_COST',
    ERROR_COST_SHIP:'ERROR_COST_SHIP',
    ERROR_SLIDER_TEXTBUTTON:'ERROR_SLIDER_TEXTBUTTON',
    ERROR_SLIDER_HEADERTITLE:'ERROR_SLIDER_HEADERTITLE',
    ERROR_SLIDER_TITLE:'ERROR_SLIDER_TITLE',
    ERROR_SLIDER_URL:'ERROR_SLIDER_URL',
    

}